version: "3.0"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=registro
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_SOURCE=postgres://root:root@postgres:5432/registro?sslmode=disable
    ports:
      - "4000:4000"
    entrypoint: ["/app/wait-for", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
