version: "3.8"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=registro

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_SOURCE="postgres://root:root@postgres:5432/registro?sslmode=disable"
    ports:
      - "4000:4000"
