// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Record struct {
	ID        string    `json:"id"`
	Unit      string    `json:"unit"`
	Value     int32     `json:"value"`
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"created_at"`
}
