// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error)
	GetRecords(ctx context.Context) ([]Record, error)
}

var _ Querier = (*Queries)(nil)
